# This is a basic workflow to help you get started with Actions

name: Build App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant Permission
        run: chmod -R 777 ./gradlew
          
      - name: Build apk
        run: ./gradlew assembleRelease

      - name: Build abb
        run: ./gradlew bundleRelease
      
